GET http://localhost:9999/api/posts

###

GET http://localhost:9999/api/posts/1

###
POST http://localhost:9999/api/posts
Content-Type: application/json

{
  "content": "Last Post2"
}

###
PATCH http://localhost:9999/api/posts
Content-Type: application/json

{
  "id": 1,
  "content": "Last Post fgbgfgbdfgbdfgbdfgbfgfgb"
}

###
DELETE http://localhost:9999/api/posts/1